# Generated by Django 5.0 on 2023-12-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('facility_type', models.CharField(blank=True, choices=[('PUSH_TRUCK', 'Push Truck'), ('TRUCK', 'Truck')], max_length=10, null=True)),
                ('cnn', models.IntegerField(blank=True, null=True)),
                ('location_description', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('block', models.CharField(blank=True, max_length=10, null=True)),
                ('lot', models.CharField(blank=True, max_length=10, null=True)),
                ('permit', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('SUSPEND', 'Suspend'), ('EXPIRED', 'Expired')], default='REQUESTED', max_length=10)),
                ('food_items', models.CharField(blank=True, max_length=256, null=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('schedule', models.CharField(blank=True, max_length=256, null=True)),
                ('days_hours', models.CharField(blank=True, max_length=256, null=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('pior_permission', models.BooleanField(blank=True, default=False, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('fire_prevention_districts', models.IntegerField(blank=True, null=True)),
                ('police_districts', models.IntegerField(blank=True, null=True)),
                ('supervisor_districts', models.IntegerField(blank=True, null=True)),
                ('zip_codes', models.IntegerField(blank=True, null=True)),
                ('neighborhoods', models.IntegerField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtruck_api.applicant')),
            ],
        ),
    ]
