# Generated by Django 5.0 on 2023-12-06 19:18

from django.db import migrations, models
import pandas


def create_applicants(apps, schema_editor):
    applicant_model = apps.get_model("foodtruck_api", "Applicant")

    absolute_path = r'C:\Users\Marcos Oliveira\PycharmProjects\P1-django-take-home-assignment\food-truck-data.csv'
    data = pandas.read_csv(absolute_path)
    unique_applicants = set(data['Applicant'].values)

    for applicant in unique_applicants:
        applicant_model.objects.create(name=applicant)


class Migration(migrations.Migration):
    dependencies = [
        ('foodtruck_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_applicants),
    ]
